# Generated by Django 4.1.1 on 2022-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_clien_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fc_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('fc_publicacion', models.DateTimeField(verbose_name='fecha publicacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Clien',
        ),
    ]
